const menuButton=document.querySelector('.menu-toggle');const menu=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const facts={spice:['Spice Girls','Mel B, Mel C, Emma, Geri y Victoria convirtieron el “Girl Power” en uno de los grandes lemas pop de los 90. Sus estilos tan distintos hacían fácil elegir favorita.'],bsb:['Backstreet Boys','A. J., Howie, Nick, Kevin y Brian fueron una de las boy bands esenciales de la década. Baladas, armonías y coreografías formaban la combinación perfecta.']};const dialog=document.querySelector('#fact-dialog');document.querySelectorAll('[data-fact]').forEach(b=>b.addEventListener('click',()=>{const [title,text]=facts[b.dataset.fact];document.querySelector('#dialog-content').innerHTML=`<h2>${title}</h2><p>${text}</p>`;dialog.showModal()}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelectorAll('[data-look]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#look-result').textContent=`Tu combinación: ${b.dataset.look}. ¡Lista para salir en la sección de moda!`}));
document.querySelector('#quiz-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(!data.get('q1')||!data.get('q2')||!data.get('q3')){document.querySelector('#quiz-result').textContent='¡Ups! Contesta las tres preguntas para conocer tu resultado.';return}const scores={a:0,b:0,c:0};for(const value of data.values())scores[value]++;const winner=Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0];const results={a:'Eres puro Girl Power: sociable, valiente y siempre pendiente de tu pandilla.',b:'Eres alma de mixtape: sensible, creativa y capaz de encontrar una canción para cada momento.',c:'Eres icono de estilo: original, atrevida y con un radar infalible para las tendencias.'};document.querySelector('#quiz-result').textContent=results[winner]});
const messages=['Una amistad necesitará tu escucha esta semana. Tu canción de la suerte tiene un estribillo irresistible.','Atrévete con ese plan que llevas días imaginando. Color de la suerte: rosa chicle.','Alguien de tu pandilla tiene una sorpresa. Lleva contigo tu mejor sonrisa.','Tu creatividad está a tope: decora la agenda, graba una cinta o inventa un look.'];document.querySelector('#sign').addEventListener('change',e=>{document.querySelector('#horoscope-result').textContent=e.target.value?`${e.target.value}: ${messages[e.target.selectedIndex%messages.length]}`:'Las estrellas aún están buscando tu mensaje…'});
document.querySelector('#club-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#form-message').textContent='¡Ya eres parte del club! (Demostración: no se ha enviado ningún dato).';e.currentTarget.reset()});document.querySelector('#year').textContent=new Date().getFullYear();

const coverButton=document.querySelector('#make-cover');coverButton.addEventListener('click',()=>{const name=document.querySelector('#cover-name').value.trim();const vibe=document.querySelector('input[name="vibe"]:checked').value;document.querySelector('#cover-output').textContent=name?`¡${name}, tú eres la estrella!`:'¡TÚ eres la estrella!';document.querySelector('#vibe-output').textContent=vibe});
const timeline={1995:['📼','Carpetas, cassettes y llamadas al fijo','Las canciones se grababan de la radio y una llamada podía durar hasta que alguien necesitaba usar el teléfono.'],1997:['🚢','Titanic, girl power y fiebre por las boy bands','El cine llenaba carpetas, las plataformas conquistaban la calle y cada pandilla elegía su Spice favorita.'],1999:['💿','El cambio de milenio sonaba a pop','Britney Spears, Ricky Martin y los CD singles acompañaban la cuenta atrás hacia el año 2000.'],2001:['📱','SMS, politonos y primeros realities','Los mensajes se escribían contando caracteres y la televisión se convertía en conversación nacional.'],2003:['💬','Messenger después de clase','Nicks con letras de canciones, zumbidos, cámaras digitales y compilaciones grabadas en CD.']};
document.querySelectorAll('.year-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.year-tab').forEach(tab=>{tab.classList.remove('active');tab.setAttribute('aria-selected','false')});button.classList.add('active');button.setAttribute('aria-selected','true');const [icon,title,text]=timeline[button.dataset.year];document.querySelector('#timeline-story').innerHTML=`<span class="timeline-emoji">${icon}</span><div><p class="eyebrow">${button.dataset.year}</p><h3>${title}</h3><p>${text}</p></div>`}));
document.querySelectorAll('.reveal-advice').forEach(button=>button.addEventListener('click',()=>{const advice=button.nextElementSibling;const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));advice.hidden=open;button.textContent=open?'Leer el consejo':'Ocultar el consejo'}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('main>.section').forEach(section=>{section.classList.add('reveal');observer.observe(section)});
